/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as FaceMakeupRouteImport } from './routes/face-makeup'
import { Route as ClothesAnalysisRouteImport } from './routes/clothes-analysis'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFaceMakeupRouteImport } from './routes/api.face-makeup'
import { Route as ApiAnalyzeRouteImport } from './routes/api.analyze'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceMakeupRoute = FaceMakeupRouteImport.update({
  id: '/face-makeup',
  path: '/face-makeup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothesAnalysisRoute = ClothesAnalysisRouteImport.update({
  id: '/clothes-analysis',
  path: '/clothes-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaceMakeupRoute = ApiFaceMakeupRouteImport.update({
  id: '/api/face-makeup',
  path: '/api/face-makeup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/clothes-analysis': typeof ClothesAnalysisRoute
  '/face-makeup': typeof FaceMakeupRoute
  '/quizzes': typeof QuizzesRoute
  '/result': typeof ResultRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/face-makeup': typeof ApiFaceMakeupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/clothes-analysis': typeof ClothesAnalysisRoute
  '/face-makeup': typeof FaceMakeupRoute
  '/quizzes': typeof QuizzesRoute
  '/result': typeof ResultRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/face-makeup': typeof ApiFaceMakeupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/clothes-analysis': typeof ClothesAnalysisRoute
  '/face-makeup': typeof FaceMakeupRoute
  '/quizzes': typeof QuizzesRoute
  '/result': typeof ResultRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/face-makeup': typeof ApiFaceMakeupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/auth'
    | '/clothes-analysis'
    | '/face-makeup'
    | '/quizzes'
    | '/result'
    | '/api/analyze'
    | '/api/face-makeup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/auth'
    | '/clothes-analysis'
    | '/face-makeup'
    | '/quizzes'
    | '/result'
    | '/api/analyze'
    | '/api/face-makeup'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/auth'
    | '/clothes-analysis'
    | '/face-makeup'
    | '/quizzes'
    | '/result'
    | '/api/analyze'
    | '/api/face-makeup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AuthRoute: typeof AuthRoute
  ClothesAnalysisRoute: typeof ClothesAnalysisRoute
  FaceMakeupRoute: typeof FaceMakeupRoute
  QuizzesRoute: typeof QuizzesRoute
  ResultRoute: typeof ResultRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiFaceMakeupRoute: typeof ApiFaceMakeupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-makeup': {
      id: '/face-makeup'
      path: '/face-makeup'
      fullPath: '/face-makeup'
      preLoaderRoute: typeof FaceMakeupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothes-analysis': {
      id: '/clothes-analysis'
      path: '/clothes-analysis'
      fullPath: '/clothes-analysis'
      preLoaderRoute: typeof ClothesAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/face-makeup': {
      id: '/api/face-makeup'
      path: '/api/face-makeup'
      fullPath: '/api/face-makeup'
      preLoaderRoute: typeof ApiFaceMakeupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AuthRoute: AuthRoute,
  ClothesAnalysisRoute: ClothesAnalysisRoute,
  FaceMakeupRoute: FaceMakeupRoute,
  QuizzesRoute: QuizzesRoute,
  ResultRoute: ResultRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiFaceMakeupRoute: ApiFaceMakeupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
